const animals2 = [
    { id: 16, sv: "Krokodil", en: "Crocodile" },
    { id: 17, sv: "Pingvin", en: "Penguin" },
    { id: 18, sv: "Noshörning", en: "Rhino" },
    { id: 19, sv: "Känguru", en: "Kangaroo" },
    { id: 20, sv: "Säl", en: "Seal" },
    { id: 21, sv: "Val", en: "Whale" },
    { id: 22, sv: "Delfin", en: "Dolphin" },
    { id: 23, sv: "Papegoja", en: "Parrot" },
    { id: 24, sv: "Orm", en: "Snake" },
    { id: 25, sv: "Ekorre", en: "Squirrel" },
    { id: 26, sv: "Falk", en: "Falcon" },
    { id: 27, sv: "Myra", en: "Ant" },
    { id: 28, sv: "Fluga", en: "Fly" },
    { id: 29, sv: "Vråk", en: "Hawk" },
    { id: 30, sv: "Spindel", en: "Spider" },
    { id: 31, sv: "Sköldpadda", en: "Turtle" },
    { id: 32, sv: "Krabba", en: "Crab" },
    { id: 33, sv: "Fjäril", en: "Butterfly" },
    { id: 34, sv: "Koala", en: "Koala" },
    { id: 35, sv: "Panda", en: "Panda" },
    { id: 36, sv: "Giraff", en: "Giraffe" },
    { id: 37, sv: "Zebra", en: "Zebra" },
    { id: 38, sv: "Papegoja", en: "Parrot" },
    { id: 39, sv: "Fiskmås", en: "Seagull" },
    { id: 40, sv: "Grävling", en: "Badger" },
    { id: 41, sv: "Utter", en: "Otter" },
    { id: 42, sv: "Krokodil", en: "Crocodile" },
    { id: 43, sv: "Lemur", en: "Lemur" },
    { id: 44, sv: "Späckhuggare", en: "Killer whale" },
    { id: 45, sv: "Flodhäst", en: "Hippo" },
    { id: 46, sv: "Råtta", en: "Rat" },
    { id: 47, sv: "Mus", en: "Mouse" },
    { id: 48, sv: "Valross", en: "Walrus" },
    { id: 49, sv: "Piggsvin", en: "Hedgehog" },
    { id: 50, sv: "Eldfluga", en: "Firefly" }
]

export default animals2;